### ISSUE TITLE
Data kelas tidak terbaca di NoteController

### ISSUE THREAD

**Issue by FakhriRyu** [FakhriRyu/UniverSaya-PBKK#5]
jadi bang untuk <i>laravel eloquentnya relationship</i> sudah selesai, di views show mata kuliah sudah bisa melihat isi catatan yang dibuat di table notes, tapi saya menemui <b>masalah</b> yang tidak bisa saya pecahkan selama 2 hari belakang ini, yaitu bagian yang <b>menampilkan pilihan mata kuliah saat menambah catatan</b> saya menggunakan foreach untuk menampilkannya namun data kelas tidak terbaca. saat saya coba <strong>dd$kelas</strong> di NoteController datanya tidak terbaca. saya coba utak atik dari routes web.php, migration, NoteModels, KelasModels, KelasController, NoteController, View, Namun tidak ada hasil dan masih tidak mau terbaca.  Sudah saya menonton banyak youtube, minta bantuan ChatGPT, stackoverflow, dll namun hasilnya masih nihil. <br>ini linknya bang https://github.com/FakhriRyu/UniverSaya-PBKK/commit/9352d41b31f48a84d50ac7eddd12881e40d7f0b4 <br>
![giphy](https://github.com/FakhriRyu/UniverSaya-PBKK/assets/144465046/f1a71bbf-c693-4dbb-9f90-78bc419063a8)

**Comment by WahyuS002** [comment]
Cara solving nya bsa lihat di sini Ri

https://www.loom.com/share/a018d38e0527472d981774ee8086f180?sid=5aabab15-afe0-4974-8916-148c012dc47d
